-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA if NOT EXISTS auth;

CREATE TABLE if NOT EXISTS auth.roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre varchar NOT NULL UNIQUE,
    descripcion varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth.status (
    id integer NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    nombre varchar NOT NULL UNIQUE,
    descripcion varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS auth.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cedula integer NOT NULL UNIQUE,
    nombre varchar NOT NULL,
    apellido varchar NOT NULL,
    telefono varchar NOT NULL,
    email varchar NOT NULL UNIQUE,
    username varchar NOT NULL UNIQUE,
    password varchar NOT NULL,
    rol_id UUID NOT NULL REFERENCES auth.roles(id),
    status_id integer NOT NULL DEFAULT 1 REFERENCES auth.status(id),
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS estados (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    nombre varchar NOT NULL UNIQUE
);

CREATE TABLE if NOT EXISTS municipios (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    nombre varchar NOT NULL,
    estado_id integer NOT NULL REFERENCES estados(id)
);

CREATE TABLE if NOT EXISTS directorios (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    nombre varchar NOT NULL,
    descripcion text,
    direccion varchar,
    telefono varchar NOT NULL,
    correo varchar,
    foto varchar,
    estado_id integer NOT NULL REFERENCES estados(id),
    municipio_id integer NOT NULL REFERENCES municipios(id),
    horario varchar,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS servicios_directorio (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    directorio_id integer NOT NULL REFERENCES directorios(id) ON DELETE CASCADE,
    servicio varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS responsables_directorio (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    directorio_id integer NOT NULL REFERENCES directorios(id) ON DELETE CASCADE,
    nombre varchar NOT NULL,
    cargo varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS redes_directorio (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    directorio_id integer NOT NULL REFERENCES directorios(id) ON DELETE CASCADE,
    nombre varchar NOT NULL,
    url varchar NOT NULL,
    icono varchar,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS requisitos_directorio (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    directorio_id integer NOT NULL REFERENCES directorios(id) ON DELETE CASCADE,
    requisito varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS courses (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    title varchar NOT NULL,
    description text NOT NULL,
    full_description text,
    instructor varchar NOT NULL,
    instructor_bio text,
    duration varchar,
    level varchar,
    image varchar,
    start_date date,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS course_modules (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title varchar NOT NULL,
    duration varchar NOT NULL,
    orden integer NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS course_requirements (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    requirement text NOT NULL,
    orden integer NOT NULL,
    created_at timestamp DEFAULT NOW()
);

CREATE TABLE if NOT EXISTS course_outcomes (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    outcome text NOT NULL,
    orden integer NOT NULL,
    created_at timestamp DEFAULT NOW()
);

-- Tabla para almacenar información institucional (contenido de la página About)
CREATE TABLE IF NOT EXISTS institucion (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    nombre varchar NOT NULL,
    nombre_corto varchar,
    fecha_creacion varchar,
    ley_creacion varchar,
    descripcion text,
    vision text,
    mision text,
    created_at timestamp DEFAULT NOW()
);

-- Valores institucionales (lista)
CREATE TABLE IF NOT EXISTS institucion_valores (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    institucion_id integer NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    titulo varchar NOT NULL,
    descripcion text,
    icono varchar, -- nombre del icono o clase CSS
    orden integer DEFAULT 0,
    created_at timestamp DEFAULT NOW()
);

-- Logros (lista de métricas/impacto)
CREATE TABLE IF NOT EXISTS institucion_logros (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    institucion_id integer NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    numero varchar NOT NULL,
    titulo varchar NOT NULL,
    descripcion text,
    orden integer DEFAULT 0,
    created_at timestamp DEFAULT NOW()
);

-- Aliados / partners
CREATE TABLE IF NOT EXISTS institucion_aliados (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    institucion_id integer NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    nombre varchar NOT NULL,
    tipo varchar,
    created_at timestamp DEFAULT NOW()
);

-- Contacto (puede haber una sola fila por institucion)
CREATE TABLE IF NOT EXISTS institucion_contacto (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    institucion_id integer NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    direccion varchar,
    telefono varchar,
    correo varchar,
    horario varchar,
    created_at timestamp DEFAULT NOW()
);

-- Redes sociales
CREATE TABLE IF NOT EXISTS institucion_redes (
    id integer PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1),
    institucion_id integer NOT NULL REFERENCES institucion(id) ON DELETE CASCADE,
    nombre varchar NOT NULL,
    url varchar NOT NULL,
    created_at timestamp DEFAULT NOW()
);