INSERT INTO auth.roles (nombre, descripcion) VALUES 
('Administrador', 'Administrador del sistema'),
('Usuario', 'Usuario del sistema');

INSERT INTO auth.status (id, nombre, descripcion) VALUES 
(1, 'Activo', 'Usuario activo'),
(2, 'Inactivo', 'Usuario inactivo'),
(3, 'Eliminado', 'Usuario eliminado');

INSERT INTO auth.users (cedula, nombre, username, email, password, rol_id) SELECT 
'12345678', 'Administrador', 'admin', 'admin@admin.com', '$2b$10$GUT8F20qqtJZkJo4m/ugpeMAvlQPwDJD.tipGSDPjXSNzB2p8FgSK', roles.id
FROM auth.roles WHERE roles.nombre = 'Administrador';

INSERT INTO estados (nombre) VALUES 
('CARACAS'),
('ANZOATEGUI'),
('APURE'),
('ARAGUA'),
('BARINAS'),
('BOLIVAR'),
('CARABOBO'),
('COJEDES'),
('FALCON'),
('GUARICO'),
('LARA'),
('MERIDA'),
('MIRANDA'),
('MONAGAS'),
('NUEVA ESPARTA'),
('PORTUGUESA'),
('SUCRE'),
('TACHIRA'),
('TRUJILLO'),
('YARACUY'),
('ZULIA'),
('AMAZONAS'),
('DELTA AMACURO'),
('VARGAS'),
('GUYANA ESEQUIBA');

INSERT INTO municipios (nombre, estado_id) VALUES 
('LIBERTADOR',1),
('ANACO',2),
('ARAGUA',2),
('BOLIVAR',2),
('BRUZUAL',2),
('CAJIGAL',2),
('FREITES',2),
('INDEPENDENCIA',2),
('LIBERTAD',2),
('MIRANDA',2),
('MONAGAS',2),
('PEÑALVER',2),
('SIMON RODRIGUEZ',2),
('SOTILLO',2),
('GUANIPA',2),
('GUANTA',2),
('PIRITU',2),
('M.L/DIEGO BAUTISTA U',2),
('CARVAJAL',2),
('SANTA ANA',2),
('MC GREGOR',2),
('S JUAN CAPISTRANO',2),
('ACHAGUAS',3),
('MUÑOZ',3),
('PAEZ',3),
('PEDRO CAMEJO',3),
('ROMULO GALLEGOS',3),
('SAN FERNANDO',3),
('BIRUACA',3),
('GIRARDOT',4),
('SANTIAGO MARIÑO',4),
('JOSE FELIX RIVAS',4),
('SAN CASIMIRO',4),
('SAN SEBASTIAN',4),
('SUCRE',4),
('URDANETA',4),
('ZAMORA',4),
('LIBERTADOR',4),
('JOSE ANGEL LAMAS',4),
('BOLIVAR',4),
('SANTOS MICHELENA',4),
('MARIO B IRAGORRY',4),
('TOVAR',4),
('CAMATAGUA',4),
('JOSE R REVENGA',4),
('FRANCISCO LINARES A.',4),
('M.OCUMARE D LA COSTA',4),
('ARISMENDI',5),
('BARINAS',5),
('BOLIVAR',5),
('EZEQUIEL ZAMORA',5),
('OBISPOS',5),
('PEDRAZA',5),
('ROJAS',5),
('SOSA',5),
('ALBERTO ARVELO T',5),
('A JOSE DE SUCRE',5),
('CRUZ PAREDES',5),
('ANDRES E. BLANCO',5),
('CARONI',6),
('CEDEÑO',6),
('HERES',6),
('PIAR',6),
('ROSCIO',6),
('SUCRE',6),
('SIFONTES',6),
('RAUL LEONI',6),
('GRAN SABANA',6),
('EL CALLAO',6),
('PADRE PEDRO CHIEN',6),
('BEJUMA',7),
('CARLOS ARVELO',7),
('DIEGO IBARRA',7),
('GUACARA',7),
('MONTALBAN',7),
('JUAN JOSE MORA',7),
('PUERTO CABELLO',7),
('SAN JOAQUIN',7),
('VALENCIA',7),
('MIRANDA',7),
('LOS GUAYOS',7),
('NAGUANAGUA',7),
('SAN DIEGO',7),
('LIBERTADOR',7),
('ANZOATEGUI',8),
('FALCON',8),
('GIRARDOT',8),
('MP PAO SN J BAUTISTA',8),
('RICAURTE',8),
('SAN CARLOS',8),
('TINACO',8),
('LIMA BLANCO',8),
('ROMULO GALLEGOS',8),
('ACOSTA',9),
('BOLIVAR',9),
('BUCHIVACOA',9),
('CARIRUBANA',9),
('COLINA',9),
('DEMOCRACIA',9),
('FALCON',9),
('FEDERACION',9),
('MAUROA',9),
('MIRANDA',9),
('PETIT',9),
('SILVA',9),
('ZAMORA',9),
('DABAJURO',9),
('MONS. ITURRIZA',9),
('LOS TAQUES',9),
('PIRITU',9),
('UNION',9),
('SAN FRANCISCO',9),
('JACURA',9),
('CACIQUE MANAURE',9),
('PALMA SOLA',9),
('SUCRE',9),
('URUMACO',9),
('TOCOPERO',9),
('INFANTE',10),
('MELLADO',10),
('MIRANDA',10),
('MONAGAS',10),
('RIBAS',10),
('ROSCIO',10),
('ZARAZA',10),
('CAMAGUAN',10),
('S JOSE DE GUARIBE',10),
('LAS MERCEDES',10),
('EL SOCORRO',10),
('ORTIZ',10),
('S MARIA DE IPIRE',10),
('CHAGUARAMAS',10),
('SAN GERONIMO DE G',10),
('CRESPO',11),
('IRIBARREN',11),
('JIMENEZ',11),
('MORAN',11),
('PALAVECINO',11),
('TORRES',11),
('URDANETA',11),
('ANDRES E BLANCO',11),
('SIMON PLANAS',11),
('ALBERTO ADRIANI',12),
('ANDRES BELLO',12),
('ARZOBISPO CHACON',12),
('CAMPO ELIAS',12),
('GUARAQUE',12),
('JULIO CESAR SALAS',12),
('JUSTO BRICEÑO',12),
('LIBERTADOR',12),
('SANTOS MARQUINA',12),
('MIRANDA',12),
('ANTONIO PINTO S.',12),
('OB. RAMOS DE LORA',12),
('CARACCIOLO PARRA',12),
('CARDENAL QUINTERO',12),
('PUEBLO LLANO',12),
('RANGEL',12),
('RIVAS DAVILA',12),
('SUCRE',12),
('TOVAR',12),
('TULIO F CORDERO',12),
('PADRE NOGUERA',12),
('ARICAGUA',12),
('ZEA',12),
('ACEVEDO',13),
('BRION',13),
('GUAICAIPURO',13),
('INDEPENDENCIA',13),
('LANDER',13),
('PAEZ',13),
('PAZ CASTILLO',13),
('PLAZA',13),
('SUCRE',13),
('URDANETA',13),
('ZAMORA',13),
('CRISTOBAL ROJAS',13),
('LOS SALIAS',13),
('ANDRES BELLO',13),
('SIMON BOLIVAR',13),
('BARUTA',13),
('CARRIZAL',13),
('CHACAO',13),
('EL HATILLO',13),
('BUROZ',13),
('PEDRO GUAL',13),
('ACOSTA',14),
('BOLIVAR',14),
('CARIPE',14),
('CEDEÑO',14),
('EZEQUIEL ZAMORA',14),
('LIBERTADOR',14),
('MATURIN',14),
('PIAR',14),
('PUNCERES',14),
('SOTILLO',14),
('AGUASAY',14),
('SANTA BARBARA',14),
('URACOA',14),
('ARISMENDI',15),
('DIAZ',15),
('GOMEZ',15),
('MANEIRO',15),
('MARCANO',15),
('MARIÑO',15),
('PENIN. DE MACANAO',15),
('VILLALBA(I.COCHE)',15),
('TUBORES',15),
('ANTOLIN DEL CAMPO',15),
('GARCIA',15),
('ARAURE',16),
('ESTELLER',16),
('GUANARE',16),
('GUANARITO',16),
('OSPINO',16),
('PAEZ',16),
('SUCRE',16),
('TUREN',16),
('M.JOSE V DE UNDA',16),
('AGUA BLANCA',16),
('PAPELON',16),
('GENARO BOCONOITO',16),
('S RAFAEL DE ONOTO',16),
('SANTA ROSALIA',16),
('ARISMENDI',17),
('BENITEZ',17),
('BERMUDEZ',17),
('CAJIGAL',17),
('MARIÑO',17),
('MEJIA',17),
('MONTES',17),
('RIBERO',17),
('SUCRE',17),
('VALDEZ',17),
('ANDRES E BLANCO',17),
('LIBERTADOR',17),
('ANDRES MATA',17),
('BOLIVAR',17),
('CRUZ S ACOSTA',17),
('AYACUCHO',18),
('BOLIVAR',18),
('INDEPENDENCIA',18),
('CARDENAS',18),
('JAUREGUI',18),
('JUNIN',18),
('LOBATERA',18),
('SAN CRISTOBAL',18),
('URIBANTE',18),
('CORDOBA',18),
('GARCIA DE HEVIA',18),
('GUASIMOS',18),
('MICHELENA',18),
('LIBERTADOR',18),
('PANAMERICANO',18),
('PEDRO MARIA UREÑA',18),
('SUCRE',18),
('ANDRES BELLO',18),
('FERNANDEZ FEO',18),
('LIBERTAD',18),
('SAMUEL MALDONADO',18),
('SEBORUCO',18),
('ANTONIO ROMULO C',18),
('FCO DE MIRANDA',18),
('JOSE MARIA VARGA',18),
('RAFAEL URDANETA',18),
('SIMON RODRIGUEZ',18),
('TORBES',18),
('SAN JUDAS TADEO',18),
('RAFAEL RANGEL',19),
('BOCONO',19),
('CARACHE',19),
('ESCUQUE',19),
('TRUJILLO',19),
('URDANETA',19),
('VALERA',19),
('CANDELARIA',19),
('MIRANDA',19),
('MONTE CARMELO',19),
('MOTATAN',19),
('PAMPAN',19),
('S RAFAEL CARVAJAL',19),
('SUCRE',19),
('ANDRES BELLO',19),
('BOLIVAR',19),
('JOSE F M CAÑIZAL',19),
('JUAN V CAMPO ELI',19),
('LA CEIBA',19),
('PAMPANITO',19),
('BOLIVAR',20),
('BRUZUAL',20),
('NIRGUA',20),
('SAN FELIPE',20),
('SUCRE',20),
('URACHICHE',20),
('PEÑA',20),
('JOSE ANTONIO PAEZ',20),
('LA TRINIDAD',20),
('COCOROTE',20),
('INDEPENDENCIA',20),
('ARISTIDES BASTID',20),
('MANUEL MONGE',20),
('VEROES',20),
('BARALT',21),
('SANTA RITA',21),
('COLON',21),
('MARA',21),
('MARACAIBO',21),
('MIRANDA',21),
('PAEZ',21),
('MACHIQUES DE P',21),
('SUCRE',21),
('LA CAÑADA DE U.',21),
('LAGUNILLAS',21),
('CATATUMBO',21),
('M/ROSARIO DE PERIJA',21),
('CABIMAS',21),
('VALMORE RODRIGUEZ',21),
('JESUS E LOSSADA',21),
('ALMIRANTE P',21),
('SAN FRANCISCO',21),
('JESUS M SEMPRUN',21),
('FRANCISCO J PULG',21),
('SIMON BOLIVAR',21),
('ATURES',22),
('ATABAPO',22),
('MAROA',22),
('RIO NEGRO',22),
('AUTANA',22),
('MANAPIARE',22),
('ALTO ORINOCO',22),
('TUCUPITA',23),
('PEDERNALES',23),
('ANTONIO DIAZ',23),
('CASACOIMA',23),
('VARGAS',24);

-- Inserciones para la tabla institucion y relacionadas (datos de example en about.tsx)
INSERT INTO institucion (id, nombre, nombre_corto, fecha_creacion, ley_creacion, descripcion, vision, mision)
VALUES (
    1,
	'Instituto Nacional de la Mujer',
	'Inamujer',
	'25 de octubre de 1999',
	'Ley de Igualdad de Oportunidades para la Mujer',
	'El Instituto Nacional de la Mujer (Inamujer) fue creado para la defensa y materialización de los derechos de la población femenina y el incremento de su participación en las misiones, planes y programas sociales del Estado, como parte de un nuevo estado de derecho para este sector.',
	'Ser el órgano rector de las políticas públicas para la igualdad de género, promoviendo el empoderamiento y bienestar de todas las mujeres en Venezuela.',
	'Ejecutar políticas públicas para la defensa permanente de los derechos humanos de las mujeres, propiciando su acceso real y efectivo a todas las esferas de la vida social en igualdad de oportunidades.'
);

-- Valores
INSERT INTO institucion_valores (institucion_id, titulo, descripcion, icono, orden)
VALUES
	(1, 'Igualdad', 'Promovemos la igualdad de oportunidades entre hombres y mujeres', 'Heart', 1),
	(1, 'Protección', 'Defendemos los derechos de las mujeres contra toda forma de violencia', 'Shield', 2),
	(1, 'Empoderamiento', 'Fomentamos la autonomía y desarrollo integral de las mujeres', 'Users', 3),
	(1, 'Justicia', 'Garantizamos el acceso a la justicia y servicios legales', 'Scale', 4);

-- Logros
INSERT INTO institucion_logros (institucion_id, numero, titulo, descripcion, orden)
VALUES
	(1, '150+', 'Centros de Atención', 'Centros operativos a nivel nacional', 1),
	(1, '500K+', 'Mujeres Atendidas', 'Atenciones directas realizadas', 2),
	(1, '24', 'Estados Cubiertos', 'Presencia en todo el territorio nacional', 3),
	(1, '98%', 'Satisfacción', 'Tasa de satisfacción de usuarias', 4);

-- Aliados
INSERT INTO institucion_aliados (institucion_id, nombre, tipo)
VALUES
	(1, 'Ministerio del Poder Popular para la Mujer', 'Gubernamental'),
	(1, 'PNUD Venezuela', 'Organismo Internacional'),
	(1, 'ONU Mujeres', 'Organismo Internacional'),
	(1, 'Fundaciones Privadas', 'Sector Privado');

-- Contacto
INSERT INTO institucion_contacto (institucion_id, direccion, telefono, correo, horario)
VALUES
	(1, 'Av. Universidad, Edificio Inamujer, Caracas, Venezuela', '+58 212 555-1234', 'contacto@inamujer.gob.ve', 'Lunes a Viernes: 8:00 AM - 5:00 PM');

-- Redes sociales
INSERT INTO institucion_redes (institucion_id, nombre, url)
VALUES
	(1, 'Instagram', '#'),
	(1, 'Facebook', '#'),
	(1, 'Twitter', '#'),
	(1, 'YouTube', '#');